############################################
### A shiny app to explore desirability  ###
############################################

#Below is the user interface code

library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
  includeCSS("style.css"),
  # Application title
  headerPanel("Desirability"),
  # Sidebar with a slider input for number of bins 
    #textOutput("Test"),
    # Show a plot of the generated distribution
    tabsetPanel(type="tabs",
                tabPanel("Diversity-fragmentation",plotOutput("div_f_plot"))
                #tabPanel("Composition",plotOutput("comp_f_plot")),
                #tabPanel("Diversity-interaction",plotOutput("kir_f_plot"))
                ),
  hr(),
  fluidRow(
    column(2,
           radioButtons("type","Weighting scheme:",c("Default"="default","All equal"="equal","Manual"="manual","Dropping functions"="drop")),
           downloadButton("dlPlot","Save graphs")),

    #conditionalPanel(
    #  condition = "input.type == 'default'",
    #  inputs <- lapply()
    #),
    conditionalPanel(
      condition = "input.type == 'manual'",
      column(2,
             h4("Soil functions"),
             sliderInput("Decomp",
                         "Litter decomposition:",
                         min = 0,
                         max = 10,
                         value = 5),
             sliderInput("C_stock",
                         "Carbon stocks:",
                         min = 0,
                         max = 10,
                         value = 7.5),
             sliderInput("BS",
                         "Base saturation:",
                         min = 0,
                         max = 10,
                         value = 6.5),
             sliderInput("pH",
                         "Topsoil pH:",
                         min = 0,
                         max = 10,
                         value = 6.5),
             sliderInput("CN",
                         "Topsoil C:N ratio:",
                         min = 0,
                         max = 10,
                         value = 6.5),
             sliderInput("P",
                         "Topsoil phosphorus:",
                         min = 0,
                         max = 10,
                         value = 6)
      ),
      column(2,
             h4("Vegetation functions"),
             sliderInput("Veg_div",
                         "Understorey diversity:",
                         min = 0,
                         max = 10,
                         value = 4.667),
             sliderInput("GLI",
                         "Light transmission:",
                         min = 0,
                         max = 10,
                         value = 6.5),
             sliderInput("LAI",
                         "Leaf area index:",
                         min = 0,
                         max = 10,
                         value = 6.75),
             sliderInput("P_germ",
                         "Seed recruitment:",
                         min = 0,
                         max = 10,
                         value = 9.33),
             sliderInput("Seed_biom",
                         "Seed growth:",
                         min = 0,
                         max = 10,
                         value = 9.33),
             sliderInput("Biomass",
                         "Tree biomass:",
                         min = 0,
                         max = 10,
                         value = 9.5),
             sliderInput("Cover",
                         "Understorey cover:",
                         min = 0,
                         max = 10,
                         value = 7)
      ),
      column(2,
             h4("Arthropod functions"),
             sliderInput("Herbivory",
                         "Herbivory:",
                         min = 0,
                         max = 10,
                         value = 7.25),
             sliderInput("Arth_div",
                         "Arthropod diversity:",
                         min = 0,
                         max = 10,
                         value = 4),
             sliderInput("Fit_spider",
                         "Spider fitness:",
                         min = 0,
                         max = 10,
                         value = 2.33),
             sliderInput("Spider_diet",
                         "Spider diet diversity:",
                         min = 0,
                         max = 10,
                         value = 3)
             
      ),
      column(2,
             h4("Bird-pathogens functions"),
             sliderInput("Egg_bact",
                         "Egg bacterial load:",
                         min = 0,
                         max = 10,
                         value = 1),
             sliderInput("Egg_IgY",
                         "Egg immunity:",
                         min = 0,
                         max = 10,
                         value = 1),
             sliderInput("Egg_vol",
                         "Egg investment:",
                         min = 0,
                         max = 10,
                         value = 1),
             sliderInput("Bird_div",
                         "Bird diversity:",
                         min = 0,
                         max = 10,
                         value = 4),
             sliderInput("Breed_succ",
                         "Bird breeding success:",
                         min = 0,
                         max = 10,
                         value = 4),
             sliderInput("Bird_smi",
                         "Bird fitness:",
                         min = 0,
                         max = 10,
                         value = 3),
             sliderInput("Predation",
                         "Predation:",
                         min = 0,
                         max = 10,
                         value = 4.5)
             
      )
      
    ),
    conditionalPanel(
      condition = "input.type == 'drop'",
      column(2,
             h4("Soil functions"),
             checkboxInput("Decomp2",
                           "Litter decomposition:",
                           value = TRUE),
             checkboxInput("C_stock2",
                           "Carbon stocks:",
                           value = TRUE),
             checkboxInput("BS2",
                           "Base saturation:",
                           value = TRUE),
             checkboxInput("pH2",
                           "Topsoil pH:",
                           value = TRUE),
             checkboxInput("CN2",
                           "Topsoil C:N ratio:",
                           value = TRUE),
             checkboxInput("P2",
                           "Topsoil phosphorus:",
                           value = TRUE)
      ),
      column(2,
             h4("Vegetation functions"),
             checkboxInput("Veg_div2",
                           "Understorey diversity:",
                           value = TRUE),
             checkboxInput("GLI2",
                           "Light transmission:",
                           value = TRUE),
             checkboxInput("LAI2",
                           "Leaf area index:",
                           value = TRUE),
             checkboxInput("P_germ2",
                           "Seed recruitment:",
                           value = TRUE),
             checkboxInput("Seed_biom2",
                           "Seed growth:",
                           value = TRUE),
             checkboxInput("Biomass2",
                           "Tree biomass:",
                           value = TRUE),
             checkboxInput("Cover2",
                           "Understorey cover:",
                           value = TRUE)
      ),
      column(2,
             h4("Arthropod functions"),
             checkboxInput("Herbivory2",
                           "Herbivory:",
                           value = TRUE),
             checkboxInput("Predation2",
                           "Predation:",
                           value = TRUE),
             checkboxInput("Arth_div2",
                           "Arthropod diversity:",
                           value = TRUE),
             checkboxInput("Fit_spider2",
                           "Spider fitness:",
                           value = TRUE),
             checkboxInput("Spider_diet2",
                           "Spider diet diversity:",
                           value = TRUE)
             
      ),
      column(2,
             h4("Bird-pathogens functions"),
             checkboxInput("Egg_bact2",
                           "Egg bacterial load:",
                           value = TRUE),
             checkboxInput("Egg_IgY2",
                           "Egg immunity:",
                           value = TRUE),
             checkboxInput("Egg_vol2",
                           "Egg investment:",
                           value = TRUE),
             checkboxInput("Bird_div2",
                           "Fledgeling immunity:",
                           value = TRUE),
             checkboxInput("Breed_succ2",
                           "Bird breeding success:",
                           value = TRUE),
             checkboxInput("Bird_smi2",
                           "Bird fitness:",
                           value = TRUE)
             
      )
    ))
))
